language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
script:
  - npm install
  - npm install if-node-version
  - if-node-version ">=4" "./node_modules/.bin/eslint . "
  - npm test
